"""initial schema

The students' project carried 18 migrations, most of them for tables this
rebuild drops (courses, Keycloak ids, roles). With no data to carry over (plan:
complete restart) they are folded into this one, generated from the models.
Until the first release it may be regenerated instead of stacking new ones.

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 15:37:41.172146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('apps',
    sa.Column('appId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('image_mime', sa.String(length=64), nullable=True),
    sa.Column('git_link', sa.String(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('hidden_by_admin', sa.Boolean(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('appId')
    )
    op.create_index('ix_apps_live', 'apps', ['appId'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_apps_userId'), 'apps', ['userId'], unique=False)
    op.create_table('user_openstack_credentials',
    sa.Column('credentialId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('auth_type', sa.Enum('v3applicationcredential', 'password', name='openstackauthtype'), nullable=False),
    sa.Column('auth_url', sa.String(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('interface', sa.String(), nullable=True),
    sa.Column('identity_api_version', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('user_domain_name', sa.String(), nullable=True),
    sa.Column('project_domain_name', sa.String(), nullable=True),
    sa.Column('encrypted_identifier', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_secret', sa.LargeBinary(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('last_validation_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('credentialId'),
    sa.UniqueConstraint('userId', 'project_id', name='uq_user_openstack_credentials_project')
    )
    op.create_index(op.f('ix_user_openstack_credentials_project_id'), 'user_openstack_credentials', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_openstack_credentials_userId'), 'user_openstack_credentials', ['userId'], unique=False)
    op.create_table('app_version_approvals',
    sa.Column('approvalId', sa.UUID(), nullable=False),
    sa.Column('appId', sa.UUID(), nullable=False),
    sa.Column('version_tag', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='appversionapprovalstatus'), nullable=False),
    sa.Column('diff_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appId'], ['apps.appId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.userId'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('approvalId'),
    sa.UniqueConstraint('appId', 'version_tag', name='uq_app_version_approval')
    )
    op.create_index(op.f('ix_app_version_approvals_appId'), 'app_version_approvals', ['appId'], unique=False)
    op.create_index(op.f('ix_app_version_approvals_reviewed_by'), 'app_version_approvals', ['reviewed_by'], unique=False)
    op.create_table('deployments',
    sa.Column('deploymentId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('releaseTag', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('os_project_id', sa.String(), nullable=False),
    sa.Column('userInputVar', sa.Text(), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('appId', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appId'], ['apps.appId'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('deploymentId')
    )
    op.create_index(op.f('ix_deployments_appId'), 'deployments', ['appId'], unique=False)
    op.create_index(op.f('ix_deployments_os_project_id'), 'deployments', ['os_project_id'], unique=False)
    op.create_index('ix_deployments_live', 'deployments', ['deploymentId'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_deployments_userId'), 'deployments', ['userId'], unique=False)
    op.create_table('tasks',
    sa.Column('taskId', sa.UUID(), nullable=False),
    sa.Column('deploymentId', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DEPLOY', 'UPDATE', 'DESTROY', 'PAUSE', 'RESUME', 'REDEPLOY', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('outputs', sa.LargeBinary(), nullable=True),
    sa.Column('current_phase', sa.String(length=50), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=True),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('state_token_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['deploymentId'], ['deployments.deploymentId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('taskId')
    )
    op.create_index(op.f('ix_tasks_deploymentId'), 'tasks', ['deploymentId'], unique=False)
    op.create_index('ix_tasks_pending', 'tasks', ['created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index('ix_tasks_unfinalized', 'tasks', ['finished_at'], unique=False, postgresql_where=sa.text('finalized_at IS NULL'))
    op.create_index('uq_tasks_active_per_deployment', 'tasks', ['deploymentId'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"))
    op.create_table('terraform_states',
    sa.Column('deploymentId', sa.UUID(), nullable=False),
    sa.Column('state', sa.LargeBinary(), nullable=True),
    sa.Column('lock_id', sa.String(), nullable=True),
    sa.Column('lock_info', sa.Text(), nullable=True),
    sa.Column('lock_task_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deploymentId'], ['deployments.deploymentId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deploymentId')
    )
    op.create_table('teams',
    sa.Column('teamId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('deploymentId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deploymentId'], ['deployments.deploymentId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teamId')
    )
    op.create_index(op.f('ix_teams_deploymentId'), 'teams', ['deploymentId'], unique=False)
    op.create_table('user_to_deployments',
    sa.Column('userToDeploymentId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('deploymentId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deploymentId'], ['deployments.deploymentId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userToDeploymentId')
    )
    op.create_index(op.f('ix_user_to_deployments_deploymentId'), 'user_to_deployments', ['deploymentId'], unique=False)
    op.create_index(op.f('ix_user_to_deployments_userId'), 'user_to_deployments', ['userId'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('taskId', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['taskId'], ['tasks.taskId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_taskId'), 'task_events', ['taskId'], unique=False)
    op.create_table('user_to_teams',
    sa.Column('userToTeamId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('teamId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['teams.teamId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userToTeamId')
    )
    op.create_index(op.f('ix_user_to_teams_teamId'), 'user_to_teams', ['teamId'], unique=False)
    op.create_index(op.f('ix_user_to_teams_userId'), 'user_to_teams', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_to_teams_userId'), table_name='user_to_teams')
    op.drop_index(op.f('ix_user_to_teams_teamId'), table_name='user_to_teams')
    op.drop_table('user_to_teams')
    op.drop_index(op.f('ix_task_events_taskId'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_user_to_deployments_userId'), table_name='user_to_deployments')
    op.drop_index(op.f('ix_user_to_deployments_deploymentId'), table_name='user_to_deployments')
    op.drop_table('user_to_deployments')
    op.drop_index(op.f('ix_teams_deploymentId'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('terraform_states')
    op.drop_index('uq_tasks_active_per_deployment', table_name='tasks', postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"))
    op.drop_index('ix_tasks_unfinalized', table_name='tasks', postgresql_where=sa.text('finalized_at IS NULL'))
    op.drop_index('ix_tasks_pending', table_name='tasks', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_tasks_deploymentId'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_deployments_userId'), table_name='deployments')
    op.drop_index('ix_deployments_live', table_name='deployments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_deployments_os_project_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_appId'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_app_version_approvals_reviewed_by'), table_name='app_version_approvals')
    op.drop_index(op.f('ix_app_version_approvals_appId'), table_name='app_version_approvals')
    op.drop_table('app_version_approvals')
    op.drop_index(op.f('ix_user_openstack_credentials_userId'), table_name='user_openstack_credentials')
    op.drop_index(op.f('ix_user_openstack_credentials_project_id'), table_name='user_openstack_credentials')
    op.drop_table('user_openstack_credentials')
    op.drop_index(op.f('ix_apps_userId'), table_name='apps')
    op.drop_index('ix_apps_live', table_name='apps', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('apps')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    # drop_table leaves the Postgres enum types behind; without this a
    # downgrade followed by an upgrade fails on "type already exists".
    for enum_type in ("tasktype", "taskstatus", "openstackauthtype", "appversionapprovalstatus"):
        op.execute(f"DROP TYPE IF EXISTS {enum_type}")
