"""The database itself refuses a second active task for one deployment.

This is the backstop ``task_service.prepare_task_in_tx`` relies on when two
requests race past its pre-check. The original project lost the index to an
autogenerated migration without anyone noticing, because the test schema came
from ``create_all`` and the index lived only in a migration.
"""

from __future__ import annotations

import pytest
from sqlalchemy.exc import IntegrityError

from appstore_api.models import Deployment, Task, TaskStatus, TaskType
from appstore_api.services import task_service
from tests.conftest import TEST_COURSE, TEST_PROJECT, TEST_SHA, create_app_in_db

pytestmark = pytest.mark.integration

_PAYLOAD = {
    "app_id": "a",
    "app_git_link": "https://example.org/a/b",
    "release": "v1",
    "user_vars": {},
    "teams": {},
    "openstack_envelope": {},
}


def _deployment(db, owner) -> Deployment:
    app = create_app_in_db(db, owner)
    dep = Deployment(commit_sha=TEST_SHA, course=TEST_COURSE, os_project_id=TEST_PROJECT, name="d", appId=app.appId, userId=owner.userId)
    db.add(dep)
    db.commit()
    return dep


def test_second_active_task_is_rejected_by_the_index(db, mock_user):
    dep = _deployment(db, mock_user)
    db.add(Task(deploymentId=dep.deploymentId, type=TaskType.DEPLOY, status=TaskStatus.RUNNING))
    db.commit()

    db.add(Task(deploymentId=dep.deploymentId, type=TaskType.DESTROY, status=TaskStatus.PENDING))
    with pytest.raises(IntegrityError, match="uq_tasks_active_per_deployment"):
        db.flush()


def test_finished_tasks_do_not_block_a_new_one(db, mock_user):
    dep = _deployment(db, mock_user)
    for status in (TaskStatus.SUCCESS, TaskStatus.FAILED, TaskStatus.CANCELLED):
        db.add(Task(deploymentId=dep.deploymentId, type=TaskType.DEPLOY, status=status))
    db.add(Task(deploymentId=dep.deploymentId, type=TaskType.DESTROY, status=TaskStatus.PENDING))
    db.commit()


def test_race_past_the_pre_check_becomes_the_domain_error(db, mock_user, monkeypatch):
    dep = _deployment(db, mock_user)
    db.add(Task(deploymentId=dep.deploymentId, type=TaskType.DEPLOY, status=TaskStatus.PENDING))
    db.commit()
    # Simulate the other request committing between our pre-check and flush.
    monkeypatch.setattr(task_service.crud_tasks, "get_tasks", lambda *_a, **_k: [])

    with pytest.raises(task_service.ActiveTaskExistsError):
        task_service.prepare_task_in_tx(db, dep.deploymentId, TaskType.DESTROY, _PAYLOAD)
